// German federal states with their geographic relationships
export interface StateDistance {
  [key: string]: {
    [key: string]: number; // Distance score 0-100
  };
}
function normalizeStateName(input: string): string {
  return input
    .toLowerCase()
    .replace(/ä/g, "ae")
    .replace(/ö/g, "oe")
    .replace(/ü/g, "ue")
    .replace(/ß/g, "ss")
    .replace(/\s+/g, "-") // thay space bằng gạch nối
    .normalize("NFD") // tách dấu Unicode
    .replace(/[\u0300-\u036f]/g, ""); // bỏ dấu còn sót
}

export function getStateDistance(state1: string, state2: string): number {
  const s1 = normalizeStateName(state1);
  const s2 = normalizeStateName(state2);

  if (!stateDistances[s1] || !stateDistances[s1][s2]) {
    return 0; // Unknown states
  }
  return stateDistances[s1][s2];
}

// Define neighboring relationships and distance scores
// 100 = same state, 80 = direct neighbor, 50 = one state between, 20 = far apart
export const stateDistances: StateDistance = {
  "baden-wuerttemberg": {
    "baden-wuerttemberg": 100,
    bayern: 80,
    hessen: 80,
    "rheinland-pfalz": 80,
    saarland: 50,
    "nordrhein-westfalen": 50,
    thueringen: 50,
    sachsen: 30,
    brandenburg: 20,
    berlin: 20,
    "mecklenburg-vorpommern": 20,
    "schleswig-holstein": 20,
    niedersachsen: 50,
    "sachsen-anhalt": 30,
    bremen: 30,
    hamburg: 30,
  },
  bayern: {
    bayern: 100,
    "baden-wuerttemberg": 80,
    hessen: 80,
    thueringen: 80,
    sachsen: 80,
    "sachsen-anhalt": 50,
    brandenburg: 50,
    "rheinland-pfalz": 50,
    saarland: 30,
    "nordrhein-westfalen": 50,
    niedersachsen: 50,
    berlin: 30,
    "mecklenburg-vorpommern": 20,
    "schleswig-holstein": 20,
    bremen: 30,
    hamburg: 30,
  },
  berlin: {
    berlin: 100,
    brandenburg: 80,
    "mecklenburg-vorpommern": 50,
    "sachsen-anhalt": 50,
    sachsen: 50,
    niedersachsen: 30,
    "schleswig-holstein": 30,
    thueringen: 50,
    bayern: 30,
    hessen: 30,
    hamburg: 50,
    bremen: 30,
    "nordrhein-westfalen": 30,
    "rheinland-pfalz": 20,
    saarland: 20,
    "baden-wuerttemberg": 20,
  },
  brandenburg: {
    brandenburg: 100,
    berlin: 80,
    sachsen: 80,
    "sachsen-anhalt": 80,
    "mecklenburg-vorpommern": 80,
    niedersachsen: 50,
    thueringen: 50,
    bayern: 50,
    "schleswig-holstein": 50,
    hamburg: 50,
    bremen: 30,
    hessen: 30,
    "nordrhein-westfalen": 30,
    "rheinland-pfalz": 20,
    saarland: 20,
    "baden-wuerttemberg": 20,
  },
  bremen: {
    bremen: 100,
    niedersachsen: 80,
    hamburg: 80,
    "schleswig-holstein": 50,
    "nordrhein-westfalen": 50,
    "sachsen-anhalt": 50,
    "mecklenburg-vorpommern": 50,
    brandenburg: 30,
    hessen: 50,
    berlin: 30,
    sachsen: 30,
    thueringen: 30,
    "rheinland-pfalz": 30,
    bayern: 30,
    "baden-wuerttemberg": 30,
    saarland: 20,
  },
  hamburg: {
    hamburg: 100,
    "schleswig-holstein": 80,
    niedersachsen: 80,
    "mecklenburg-vorpommern": 80,
    bremen: 80,
    brandenburg: 50,
    "sachsen-anhalt": 50,
    berlin: 50,
    "nordrhein-westfalen": 50,
    hessen: 30,
    sachsen: 30,
    thueringen: 30,
    "rheinland-pfalz": 30,
    bayern: 30,
    "baden-wuerttemberg": 30,
    saarland: 20,
  },
  hessen: {
    hessen: 100,
    "nordrhein-westfalen": 80,
    "rheinland-pfalz": 80,
    "baden-wuerttemberg": 80,
    bayern: 80,
    thueringen: 80,
    niedersachsen: 80,
    saarland: 50,
    sachsen: 50,
    "sachsen-anhalt": 50,
    brandenburg: 30,
    berlin: 30,
    bremen: 50,
    hamburg: 30,
    "mecklenburg-vorpommern": 20,
    "schleswig-holstein": 30,
  },
  "mecklenburg-vorpommern": {
    "mecklenburg-vorpommern": 100,
    "schleswig-holstein": 80,
    brandenburg: 80,
    niedersachsen: 50,
    hamburg: 80,
    "sachsen-anhalt": 50,
    berlin: 50,
    bremen: 50,
    sachsen: 30,
    thueringen: 30,
    "nordrhein-westfalen": 30,
    hessen: 20,
    "rheinland-pfalz": 20,
    bayern: 20,
    "baden-wuerttemberg": 20,
    saarland: 20,
  },
  niedersachsen: {
    niedersachsen: 100,
    bremen: 80,
    hamburg: 80,
    "schleswig-holstein": 80,
    "nordrhein-westfalen": 80,
    hessen: 80,
    "sachsen-anhalt": 80,
    thueringen: 50,
    "mecklenburg-vorpommern": 50,
    brandenburg: 50,
    "rheinland-pfalz": 50,
    berlin: 30,
    sachsen: 30,
    bayern: 50,
    "baden-wuerttemberg": 50,
    saarland: 30,
  },
  "nordrhein-westfalen": {
    "nordrhein-westfalen": 100,
    niedersachsen: 80,
    hessen: 80,
    "rheinland-pfalz": 80,
    saarland: 50,
    "baden-wuerttemberg": 50,
    bremen: 50,
    hamburg: 50,
    bayern: 50,
    thueringen: 50,
    "sachsen-anhalt": 50,
    "schleswig-holstein": 50,
    brandenburg: 30,
    berlin: 30,
    sachsen: 30,
    "mecklenburg-vorpommern": 30,
  },
  "rheinland-pfalz": {
    "rheinland-pfalz": 100,
    saarland: 80,
    "nordrhein-westfalen": 80,
    hessen: 80,
    "baden-wuerttemberg": 80,
    bayern: 50,
    niedersachsen: 50,
    thueringen: 50,
    sachsen: 30,
    "sachsen-anhalt": 30,
    bremen: 30,
    hamburg: 30,
    brandenburg: 20,
    berlin: 20,
    "mecklenburg-vorpommern": 20,
    "schleswig-holstein": 20,
  },
  saarland: {
    saarland: 100,
    "rheinland-pfalz": 80,
    "baden-wuerttemberg": 50,
    hessen: 50,
    "nordrhein-westfalen": 50,
    bayern: 30,
    niedersachsen: 30,
    thueringen: 30,
    sachsen: 20,
    "sachsen-anhalt": 20,
    brandenburg: 20,
    berlin: 20,
    bremen: 20,
    hamburg: 20,
    "mecklenburg-vorpommern": 20,
    "schleswig-holstein": 20,
  },
  sachsen: {
    sachsen: 100,
    thueringen: 80,
    "sachsen-anhalt": 80,
    brandenburg: 80,
    bayern: 80,
    berlin: 50,
    hessen: 50,
    niedersachsen: 30,
    "mecklenburg-vorpommern": 30,
    "nordrhein-westfalen": 30,
    "rheinland-pfalz": 30,
    "baden-wuerttemberg": 30,
    hamburg: 30,
    bremen: 30,
    "schleswig-holstein": 20,
    saarland: 20,
  },
  "sachsen-anhalt": {
    "sachsen-anhalt": 100,
    niedersachsen: 80,
    thueringen: 80,
    sachsen: 80,
    brandenburg: 80,
    berlin: 50,
    "mecklenburg-vorpommern": 50,
    hessen: 50,
    bremen: 50,
    hamburg: 50,
    bayern: 50,
    "nordrhein-westfalen": 50,
    "schleswig-holstein": 30,
    "rheinland-pfalz": 30,
    "baden-wuerttemberg": 30,
    saarland: 20,
  },
  "schleswig-holstein": {
    "schleswig-holstein": 100,
    hamburg: 80,
    niedersachsen: 80,
    "mecklenburg-vorpommern": 80,
    bremen: 50,
    brandenburg: 50,
    "nordrhein-westfalen": 50,
    "sachsen-anhalt": 30,
    berlin: 30,
    hessen: 30,
    thueringen: 20,
    "rheinland-pfalz": 20,
    bayern: 20,
    "baden-wuerttemberg": 20,
    sachsen: 20,
    saarland: 20,
  },
  thueringen: {
    thueringen: 100,
    hessen: 80,
    bayern: 80,
    sachsen: 80,
    "sachsen-anhalt": 80,
    niedersachsen: 50,
    brandenburg: 50,
    "nordrhein-westfalen": 50,
    "rheinland-pfalz": 50,
    berlin: 50,
    "baden-wuerttemberg": 50,
    "mecklenburg-vorpommern": 30,
    bremen: 30,
    hamburg: 30,
    "schleswig-holstein": 20,
    saarland: 30,
  },
};

// Display names for federal states
export const stateDisplayNames: { [key: string]: string } = {
  "baden-wuerttemberg": "Baden-Württemberg",
  bayern: "Bayern",
  berlin: "Berlin",
  brandenburg: "Brandenburg",
  bremen: "Bremen",
  hamburg: "Hamburg",
  hessen: "Hessen",
  "mecklenburg-vorpommern": "Mecklenburg-Vorpommern",
  niedersachsen: "Niedersachsen",
  "nordrhein-westfalen": "Nordrhein-Westfalen",
  "rheinland-pfalz": "Rheinland-Pfalz",
  saarland: "Saarland",
  sachsen: "Sachsen",
  "sachsen-anhalt": "Sachsen-Anhalt",
  "schleswig-holstein": "Schleswig-Holstein",
  thueringen: "Thüringen",
};
